version: '3.7'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=America/Sao_Paulo"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=America/Sao_Paulo"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
    ports:
      - 9201:9201
    networks:
      - elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=America/Sao_Paulo"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./config/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
    ports:
      - 9202:9202
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: "dgNIOeRwiokVKdpJjbIJ"
      SERVER_HOST: "0.0.0.0"
      TZ: "America/Sao_Paulo"  
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic

#  logstash:
#    image: logstash:8.7.0
#    command: bash -c "bin/logstash-plugin install logstash-output-exec && bin/logstash"
#    container_name: logstash
#    restart: unless-stopped
#    volumes:
#      #- type: bind
#      #  source: ./logstash/config/logstash.yml
#      #  target: /usr/share/logstash/config/logstash.yml
#      #  read_only: true
#      - type: bind
#        source: /Users/anderson/softvaro/sofia/financial/sofianow-logstash-financial/lib/jdbc/mysql-connector-java-8.0.11.jar
#        target: /usr/share/logstash/lib/jdbc/mysql-connector-java-8.0.11.jar
#        read_only: true
#      - type: bind
#        source: /Users/anderson/softvaro/sofia/financial/sofianow-logstash-financial/pipeline/pipelines.yml
#        target: /usr/share/logstash/config/pipelines.yml
#        read_only: true
#      - type: bind
#        source: /Users/anderson/softvaro/sofia/financial/sofianow-logstash-financial/pipeline/conf
#        target: /usr/share/logstash/pipeline/conf
#        read_only: true
#    ports:
#      - "6000:5000/tcp"
#      - "6000:5000/udp"
#      - "9600:9600"
#    environment:
#      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
#      TZ: "America/Sao_Paulo"
#      ELASTICSEARCH_USER: "logstash"
#      ELASTICSEARCH_PASSWORD: "2Eq45JFfX2FDwS"
#      ELASTICSEARCH_USER_NOW: "now-financial"
#      ELASTICSEARCH_PASSWORD_NOW: "yVY4kAy4t89wAY"
#    depends_on:
#      - es01

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
